general.import = [
    "~/.config/alacritty/matugen-alacritty.toml",
]

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 7
y = 7
