[config.wallpaper]
command = "swww"
arguments = ["img", "transition-type", "center"]
set = true

[templates.alacritty]
input_path = "./templates/matugen-alacritty.toml"
output_path = "~/.config/alacritty/matugen-alacritty.toml"

[templates.rofi]
input_path = "./templates/matugen-rofi.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.lualine]
input_path = "./templates/matugen-lualine.lua"
output_path = "~/.local/share/nvim/lazy/lualine.nvim/lua/lualine/themes/matugen-lualine.lua"

[templates.qtct]
input_path = "./templates/matugen-qtct.conf"
output_path = "~/.config/qt6ct/colors/matugen-qtct.conf"

[templates.gtk3]
input_path = "./templates/matugen-gtk.css"
output_path = "~/.config/gtk-3.0/colors.css"

[templates.gtk4]
input_path = "./templates/matugen-gtk.css"
output_path = "~/.config/gtk-4.0/colors.css"

[templates.tmux]
input_path = "./templates/matugen-tmux.conf"
output_path = "~/.config/tmux/matugen-tmux.conf"
