# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

# Center godot popups
windowrule {
    name = "Center godot popups"
    size = 70% 60%
    center = on
    match:class = initialClass:(Godot)
    match:title = (\w)
}

windowrule {
    name = "Center Volume control applet"
    float = on
    match:title = Volume Control
    min_size = 800 500
}

windowrule {
    name = "Open vesktop in workspace"
    workspace = 4 silent
    match:class = vesktop
}

windowrule {
    name = "Open Keepass in workspace"
    workspace = 9 silent
    match:class = org.keepassxc.KeePassXC 
}
