hl.on("hyprland.start", function()
    hl.exec_cmd("~/dotfiles/hypr/scripts/xdg.sh")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("swaync")
    hl.exec_cmd("waybar")
    hl.exec_cmd("~/dotfiles/hypr/scripts/gtk.sh")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("~/dotfiles/hypr/scripts/eww.sh")
    hl.exec_cmd("keepassxc", { workspace = "9" })
    hl.exec_cmd("corectrl", { workspace = "8" })
    hl.exec_cmd("syncthing")
    hl.exec_cmd("~/dotfiles/.settings/browser.sh", { workspace = "1" })
    hl.exec_cmd("~/dotfiles/.settings/terminal.sh", { workspace = "2" })
    hl.exec_cmd("vesktop", { workspace = "4" })
    hl.exec_cmd("~/dotfiles/hypr/scripts/cleanup.sh")
    hl.exec_cmd("systemctl stop dunst --user")
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("~/.config/ml4w-hyprland-settings/hyprctl.sh")
end)
