# ----------------------------------------------------- 
# ML4W configurations
# ----------------------------------------------------- 

env = APPIMAGELAUNCHER_DISABLE,1
env = XDG_CURRENT_DESKTOP,Hyprland
